### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by Zibri** [homeryan/dht-infohash-crawler#1]
# node index.js 
/home/zibri/dhttest/dht-infohash-crawler/example/index.js:14
let crawlerCounter = 0;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by ralyodio** [comment]
just change the file to .ejs

**Comment by Zibri** [comment]
I don't know what you mean..
